### ISSUE TITLE
Calculator 

### ISSUE THREAD

**Issue by TamaraG13** [alptium/tamara.golubovic#3]

**Comment by TamaraG13** [comment]
Done :) @valentinacupac

**Comment by valentinajemuovic** [comment]
@TamaraG13:

https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World - see 39, 29.

Also, where is multiplication and division occurring?

**Comment by TamaraG13** [comment]
Task done @valentinacupac

**Comment by valentinajemuovic** [comment]
@TamaraG13, see https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 2, see comment 29.

**Comment by TamaraG13** [comment]
I have corrected this task, please check it @valentinacupac

**Comment by valentinajemuovic** [comment]
@TamaraG13, still not fixed, I'll move it to be reviewed during the next meeting.

**Comment by valentinajemuovic** [comment]
@TamaraG13: 
* comment 2: Calculator rename to calculator.
* comment 29: Done
* Indentation: line 82
* When printing labels "The result is: " + x;

Program correctness - ok.

**Comment by valentinajemuovic** [comment]
@TamaraG13, correct.
